#ifndef CODEGEN_H
#define CODEGEN_H

std::ofstream compiled("program.asm");

void CodeGenCreateStart()
{
    compiled << "; Generated by HuguiniCompiler" << std::endl;
    compiled << "global _start" << std::endl
             << std::endl;
    compiled << "_start:" << std::endl;
}

void CodeGenCreateReturn(Token *anotherToken)
{
    compiled << "    mov rax, 60" << std::endl;
    compiled << "    mov rdi, " << anotherToken->value << std::endl;
    compiled << "    syscall" << std::endl;
}

#endif