#ifndef CODEGEN_H
#define CODEGEN_H

std::ofstream compiled("program.asm");

void CodeGenCreateStart()
{
    compiled << "; Generated by HuguiniCompiler" << std::endl;
    compiled << "global _start" << std::endl
             << std::endl;
    compiled << "_start:" << std::endl;
}

void CodeGenCreateReturn(Token *anotherToken)
{
    compiled << "    ; return " << " " << anotherToken->value << ";" << std::endl;
    compiled << "    mov rax, 60" << std::endl;
    compiled << "    mov rdi, " << anotherToken->value << std::endl;
    compiled << "    syscall" << std::endl << std::endl;
}

void CodeGenCreateVariable(Token* anotherToken, Token* anotherToken3) {
    compiled << anotherToken->value << "        dw          " << anotherToken3->value;
    compiled << "      ; int " << anotherToken->value << " = " << anotherToken3->value << ";" << std::endl;
}

#endif